services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:root@db:5432/mira
        BETTER_AUTH_URL: ${BETTER_AUTH_URL}
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
        NEXT_PUBLIC_LOCATIONIQ_API_KEY: ${NEXT_PUBLIC_LOCATIONIQ_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/mira
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - NEXT_PUBLIC_LOCATIONIQ_API_KEY=${NEXT_PUBLIC_LOCATIONIQ_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mira
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: